const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),C=require('../core.js');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,''));
const bank=C.validateQuestions(['data/v1-questions.json','data/original-questions.json','data/open-questions.json','data/recalled-questions.json'].flatMap(read));
const sourceData=read('research/sources.json');
const resources=Array.isArray(sourceData)?sourceData:(sourceData.resources||sourceData.sources||[]);
const data={version:'2026.09.20-r2',questions:bank,resources};
fs.writeFileSync(path.join(root,'data.js'),'window.BANK_DATA = '+JSON.stringify(data,null,2)+';\n');
const files=['index.html','styles.css','core.js','app.js','data.js','icon.svg','manifest.webmanifest','ATTRIBUTION.html'];
const hash=crypto.createHash('sha256').update('install-http-cache-reload-v2');
for(const file of files)hash.update(fs.readFileSync(path.join(root,file)));
const version=hash.digest('hex').slice(0,12);
const sw=`/* Static assets only; user progress is never cached or uploaded. */\nconst CACHE='bank-quiz-${version}';\nconst FILES=${JSON.stringify(['./',...files.map(f=>'./'+f)])};\nself.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES.map(p=>new Request(p,{cache:'reload'}))))));\nself.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting();});\nself.addEventListener('activate',e=>e.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('bank-quiz-')&&k!==CACHE).map(k=>caches.delete(k)))),self.clients.claim()])));\nself.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).origin!==self.location.origin)return;const url=new URL(e.request.url);if(!url.pathname.startsWith(new URL('./',self.location.href).pathname))return;e.respondWith(caches.open(CACHE).then(async c=>{const cached=await c.match(e.request,{ignoreSearch:true});return cached||fetch(e.request);}));});\n`;
fs.writeFileSync(path.join(root,'sw.js'),sw);
fs.mkdirSync(path.join(root,'docs'),{recursive:true});
for(const file of [...files,'sw.js'])fs.copyFileSync(path.join(root,file),path.join(root,'docs',file));
fs.writeFileSync(path.join(root,'docs','.nojekyll'),'');
const counts=Object.fromEntries(['official_past','recalled','publication','open','original'].map(k=>[k,bank.filter(q=>q.source.kind===k).length]));
console.log('BUILD=PASS; QUESTIONS='+bank.length+'; SOURCES='+JSON.stringify(counts)+'; CACHE='+version);
